version: '3.9'

# ============================================
# Docker Compose - Aplot Frontend
# ============================================

services:
  # ==========================================
  # Frontend - Aplicação Next.js
  # ==========================================
  frontend:
    container_name: aplot-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - aplot-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ==========================================
  # Nginx - Proxy Reverso (Opcional)
  # ==========================================
  nginx:
    container_name: aplot-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - aplot-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  aplot-network:
    driver: bridge
    name: aplot-network

